# Generated by Django 6.0.6 on 2026-07-02 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in lists and meta tags.')),
                ('body', models.TextField(help_text='Plain text; blank lines start new paragraphs.')),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, help_text="Mono label in the left column, e.g. 'Computer vision · 2025'.", max_length=100)),
                ('description', models.TextField()),
                ('stack', models.CharField(blank=True, help_text="Comma-separated technologies, e.g. 'YOLOv8, Python, OpenCV'.", max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, help_text="Optional preview image, revealed on hover. On Render's free tier uploads reset on redeploy; the static path below survives.", upload_to='projects/')),
                ('image_static', models.CharField(blank=True, help_text="Path under static/, e.g. 'img/projects/producty.webp'. Used when no image is uploaded.", max_length=200)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Prajnan MJ', max_length=100)),
                ('site_name', models.CharField(default='prajnan.dev', max_length=100)),
                ('eyebrow', models.CharField(default='Applied AI · Full-stack engineering', help_text='Small mono label above the hero headline.', max_length=200)),
                ('intro', models.TextField(default='I build computer-vision and LLM systems that hold up in production — detection pipelines, AI assistants, and the full stack around them.')),
                ('about', models.TextField(default='Software developer specializing in applied AI and full-stack engineering. YOLOv8, LLMs, FastAPI, React — building things that work in production.', help_text='Large serif statement in the About section.')),
                ('currently', models.CharField(blank=True, default='MSc Mathematics @ BITS Pilani, K K Birla Goa Campus (2025–2030)', help_text="One-line 'currently' note under the About statement.", max_length=250)),
                ('email', models.EmailField(default='mj.prajnan@gmail.com', max_length=254)),
                ('github_url', models.URLField(default='https://github.com/Prajnan-mj')),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/prajnan-m-j-82798630b/')),
                ('resume', models.FileField(blank=True, help_text="Upload a PDF. Note: on Render's free tier uploaded files reset on redeploy — a resume URL below is more durable.", upload_to='resume/')),
                ('resume_url', models.URLField(blank=True, help_text='Alternative to uploading: link to a hosted resume (Google Drive, GitHub, etc.). Used if no file is uploaded.')),
                ('availability', models.CharField(default='Open to roles and collaborations in applied AI and full-stack engineering.', max_length=250)),
                ('background_theme', models.CharField(choices=[('a', 'Breathing (A)'), ('b', 'Drift (B)'), ('c', 'Journey (C)')], default='a', help_text='Which neural-mesh background strip to use site-wide.', max_length=1)),
                ('meta_description', models.CharField(default='Prajnan MJ — software developer specializing in applied AI and full-stack engineering. YOLOv8, LLMs, FastAPI, React, Django.', max_length=300)),
            ],
            options={
                'verbose_name': 'site profile',
                'verbose_name_plural': 'site profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(default='Other', help_text="Group label, e.g. 'AI / ML', 'Backend', 'Frontend', 'Tools'.", max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('project', 'Project'), ('award', 'Award')], default='experience', max_length=20)),
                ('period', models.CharField(help_text="e.g. '2025 — 2030' or '2025 — Present'.", max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'timeline entries',
                'ordering': ['order', 'id'],
            },
        ),
    ]
